feat: new userOp structure for EPv0.7
bcnmy/bundler pull request #677
Opened 2024-08-26 11:57 UTC by veljkovranic

# 📖 Context
## Type of change

- [x] Non-breaking change (backwards compatible)

## Why are we doing this?

ERC-4337 got a new update with EntryPoint v0.7, which affected the UserOps structure.

The new object doesn't contain initCode and paymasterAndData fields (as in used to up to EPv0.6),
and it introduced new fields: factor, factoryData, paymaster, paymasterVerificationGasLimit, paymasterPostOpGasLimit, and paymasterData.

All this can be found at https://eips.ethereum.org/EIPS/eip-4337#useroperation

Related issues:
[link to issue](https://github.com/bcnmy/bundler/issues/671)

## What did we do?

- We changed interface of several client-facing endpoints (only v3 version)
- Changed the underlying structure that is stored in the Mongo
- Added a new queue type for new object (as well as its appropriate consumers and producers)
- Fix the old tests

## How Has This Been Tested?

- Tested this manually by sending a user op on the Base Sepolia network 
 (here is a link to the successful transactions against EPv0.7 contract - https://sepolia.basescan.org/tx/0xb48b098665b1d74a8d26e02a8549af270113cf147232de08088406de28fa87e3 )

- More thorough testing is still pending (tbd)

# 👀 How do I review this?
- To test this you first need to checkout this branch and run the Nexus SDK against v3 set of endpoints

Instructions for calling new set of endpoints are here:

git clone https://github.com/bcnmy/biconomy-client-sdk.git
git checkout feat/nexus-pm

setup 
```
E2E_PRIVATE_KEY_ONE=
E2E_PRIVATE_KEY_TWO=
BUNDLER_URL=
PAYMASTER_URL=
CHAIN_ID=
E2E_BICO_PAYMASTER_KEY_AMOY=_sTfkyAEp.552504b5-9093-4d4b-94dd-701f85a267ea
E2E_BICO_PAYMASTER_KEY_BASE=1SiNJ1OW7.e15b6f41-5ed4-493a-af6f-b3b40c17f856
```

in .env

bun install
bun run build
bun run scripts/send:userOp.ts

2024-09-04 15:19 UTC, TheDivic commented
@veljkovranic please add instructions how do I run the Nexus SDK and test the new v7 endpoints.

2024-09-04 15:23 UTC, TheDivic commented on src/common/db/dao/UserOperationV07DAO.ts
> +              { creationTime: { $gte: startTime } },
Can you check if we have Mongo indexes on these fields?

It's also a good opportunity to setup a connection to our MongoDB and browse the data if you didn't do it so far.
@TakGN can give you instructions how to connect to the prod database.

2024-09-04 15:25 UTC, TheDivic commented on src/common/entrypoint-v7/PackedUserOperation.ts
> +export function packInitCode(userOperation: UserOperationStruct): Hex {
Missing docstring explaining how this packing works

2024-09-04 15:27 UTC, TheDivic commented on src/common/maps/index.ts
> +  [TransactionType.BUNDLER_V3]: "RM2",
Hmm this doesn't look right. we should use the same relayer manager as before.
@arcticfloyd1984 can you confirm?

2024-09-04 15:28 UTC, TheDivic commented on src/common/simulation/BundlerSimulationService.v7.ts
> +      userOp.callGasLimit = BigInt(58000);
Shouldn't we read this from the config?

2024-09-04 15:31 UTC, TheDivic requested changes
Overall this is a lot of work an a great job.
I left some less important "style" related comments that you can optionally take into account.

Only two things that worry me:
- The relayer manager issue I mentioned
- I need instructions how to test this locally with Nexus

2024-09-05 07:12 UTC, arcticfloyd1984 submitted a review, later dismissed

2024-09-05 07:12 UTC, arcticfloyd1984 commented on src/common/db/mongo/Mongo.ts
>      } catch (error) {
We probably should not log this. It will have username and password of the database.

2024-09-05 07:12 UTC, arcticfloyd1984 commented on src/common/db/mongo/interface/IUserOperationV07.ts
> +  maxPriorityFeePerGas: number;
`paymasterVerificationGasLimit` and `paymasterPostOpGasLimit` are missing

2024-09-05 07:12 UTC, arcticfloyd1984 commented on src/common/entrypoint-v7/PackedUserOperation.ts
>  ];
Don't hardcode this, the address can be different on some chains

2024-09-05 07:12 UTC, arcticfloyd1984 commented on src/common/entrypoint-v7/PackedUserOperation.ts
> +  postOpGasLimit: bigint
Please use correct names that are mentioned in the spec `paymasterVerificationGasLimit` and  `paymasterPostOpGasLimit`

2024-09-05 07:12 UTC, arcticfloyd1984 commented on src/common/service-manager/index.ts
> +        if (!EVMRelayerManagerMap.RM2) {
We don't need a new Relayer Manager for a new entry point

2024-09-11 13:24 UTC, TheDivic commented on src/common/simulation/BundlerSimulationService.v7.ts
> +      // // for userOp completeness
Why are we commenting this out instead of deleting?

2024-09-11 13:26 UTC, TheDivic commented on src/config/static-config.json
> -  "nonRM2SupportedNetworks": [
@veljkovranic I think that we can safely delete the whole `statis-config.json` file, it was used in the past and was left in the codebase just for reference.

2024-09-11 13:27 UTC, TheDivic commented on src/relayer/transaction-listener/EVMTransactionListener.ts
> +          } else {
This code is a bit unreadable and looks like a 🎄 but it's not that important, we can leave it for later.

2024-09-11 13:28 UTC, TheDivic approved these changes
LGTM, thanks for the good comments in code and docstrings! 🏆

2024-09-11 13:36 UTC, merged